### ISSUE TITLE
Introduce go linting to CI process

### ISSUE THREAD

**Issue by zendern** [sonatype-nexus-community/nancy#65]
* **What are you trying to do?**

The issue that spurred PR #59 was found via running a go linter. https://github.com/golangci/golangci-lint to be specific. But we should get this or at a dead minimum `go vet` in place as part of our CI pipeline. This will help our code suck less. 

* **What feature or behavior is this required for?**
Doing linting on all PRs and master builds

* **How could we solve this issue? (Not knowing is okay!)**
Introduce `golangci-lint` or `go vet` as part of the build process. 

* **Anything else?**
`golangci-lint` has a lot of configurability as well as lots more linters/tools that come with that have the ability to help find and fix issues. Whereas `go vet` is a do one thing and only that thing. It did point out the same issue fixed as part of #59 but that was it. 

`golangci-lint` does in fact run `go vet` as part of its process. 

The defaults for `golangci-lint` are as follows : 
![image](https://user-images.githubusercontent.com/1099906/70584342-c608e880-1b8e-11ea-9280-22be1f718535.png)

@flimzy mentioned that he likes to configure some others that are not enabled by default so hopefully they will fill us in on those details and we can discuss further. 

I currently dont have strong opinions on what we enable at the moment. At this point getting either in place or even a different option is better than the nothing we have today.

cc @bhamail / @DarthHater / @flimzy

**Comment by zendern** [comment]
As part of this we will have to triage/fix what is bad in the existing codebase as well since we will want the builds to fail if the linting tool comes back with any issues.

**Comment by flimzy** [comment]
IMHO, the minimum responsible configuration for go linting is `govet` and `errcheck`. These routinely find real bugs in code I work on.

`gofmt` is also almost a no-brainier to include (even though the gofmt authors say not to run it in CI, since it can change between Go versions--this has yet to be a serious problem for me, though).

For reference, in case anyone cares, this is the standard config I use on my projects, which only reflects my personal opinion on what matters, and should in no way be considered a universal ideal :)

```toml
[output]
format = "colored-line-number"

[linters]
enable = [
    "interfacer", "gocyclo", "unconvert", "goimports", "unused", "varcheck",
    "vetshadow", "misspell", "nakedret", "errcheck", "golint", "ineffassign",
    "deadcode", "goconst", "vet", "unparam", "gofmt"
]
```
